name: admin-ui-call-filter
namespace: official
version: 1.0.1-1
author: Wazo Team
display_name: BS Filters
min_wazo_version: 18.03
tags:
  - BS Filter
homepage: https://github.com/wazo-pbx/wazo-admin-ui-call-filter
