name: admin-ui-callfilter
namespace: official
version: 1.0.0-1
author: Wazo Team
display_name: Callfilters
min_wazo_version: 18.02
tags:
  - callfilter
homepage: https://github.com/wazo-pbx/wazo-admin-ui-callfilter
